### ISSUE TITLE
Merlin didn't work on OCaml 4.13

### ISSUE THREAD

**Issue by ahmadrasyidsalim** [ocaml/merlin#1417]
Using ```PKG``` directive followed by ```base```, ```PKG base``` on `.merlin` didn't work out, '_Unbound module Base_'

````sh
$ ocaml --version
The OCaml toplevel, version 4.13.1


$ opam list search merlin
# Packages matching: (installed | available) & (name-match(search) | name-match(merlin))
# Name # Installed # Synopsis
merlin 4.4-413     Editor helper, provides completion, typing and source browsing in Vim and Emacs


$ opam list search ocaml-lsp-server
# Packages matching: (installed | available) & (name-match(search) | name-match(ocaml-lsp-server))
# Name           # Installed # Synopsis
ocaml-lsp-server 1.9.1       LSP Server for OCaml
````

**Comment by voodoos** [comment]
Hello @ahmadrasyidsalim, we need more details to be able to help you.

What editor are you using ? Emacs, vim or vscode ?

If you use vscode with `ocaml-lsp-server` and the `ocaml-platform` extension then you should be aware that they dropped support for `.merlin` config recently (see https://github.com/ocaml/ocaml-lsp/pull/523). That means that you must build your project with Dune for `ocaml-lsp-server` to work as expected.

**Comment by ahmadrasyidsalim** [comment]
Pardon me, I'm using Neovim + coc.nvim

**Comment by voodoos** [comment]
So looking at `coc.nvim` it is a client for the LSP protocol, and it interacts with `ocaml-lsp-server`.
That means that `.merlin` files are ignored in favour of Dune-generated configuration due to the change I mentioned in my previous post.

You can either:
- use a plugin that directly talks with Merlin (and I don't know neovim so I cannot suggest anything)
- switch to Dune to build your project 
- or argue in @ocaml/ocaml-lsp issue tracker that they should restore support for `.merlin` files (which is unlikely).

I am closing since this is not a Merlin issue.
