### ISSUE TITLE
correct fields of incorrect record expression are dropped

### ISSUE THREAD

**Issue by AllanBlanchard** [ocaml/merlin#1369]
In the following example:

```ocaml
type t = C of int
type record = { field : t; other : bool; }

let f () =
  let field = 42 in
  { field (* <--- asking the type for this field *) = C field ; other = true }
```
We get `int` instead of `t`. I get this result both with Emacs and VSCode.

Note that, if we remove field `other`, then getting a code like this:

```ocaml
type t = C of int
type record = { field : t; }

let f () =
  let field = 42 in
  { field (* <--- asking the type for this field *) = C field }
```

We correctly get `t`.

Other behavior, if we remove the local `field` variable, thus getting the following code:

```ocaml
type t = C of int
type record = { field : t; other : bool; }

let f () =
  { field (* <--- asking the type for this field *) = C 42 ; other = true }
```
We get the error `Unbound value field` on Emacs and I can't ask the type of `field` on VSCode.

I found an issue that seems to be related: https://github.com/ocaml/merlin/issues/864. It was fixed in https://github.com/ocaml/merlin/pull/1108, thus Merlin version 3.3.5. I am currently using 4.2-411 with OCaml 4.11.0.

**Comment by ulugbekna** [comment]
![image](https://user-images.githubusercontent.com/16353531/127180259-49261bff-9083-4d99-951a-db3767966d6a.png)

Seems fine to me with the ocaml-lsp master. Since the user reported a specific merlin version, I think they don't use ocaml-lsp.

**Comment by voodoos** [comment]
I was on your construct branch :-)

But the issue persists after upgrading to 1.7.0:
<img width="385" alt="image" src="https://user-images.githubusercontent.com/5031221/127196304-6c03f14f-f044-4840-8264-4a35f86331c4.png">

(new file, no build)

>  Since the user reported a specific merlin version, I think they don't use ocaml-lsp.
He also mentioned VSCode so he is probably using `ocaml-lsp` too ?

**Comment by ulugbekna** [comment]
> I was on your construct branch :-)

I should've let you know that we merged it into master (along with `refactor-open` support and other cool things), so you can pin master now :-) 

> He also mentioned VSCode so he is probably using ocaml-lsp too ?

Sorry, I missed it. 

--- 

The ocaml-lsp master branch doesn't have this problem, so @AllanBlanchard you can `opam pin` the master of ocaml-lsp, if you want. 

We can probably close this issue.

**Comment by AllanBlanchard** [comment]
>  Or maybe you use OCaml-LSP for emacs too ?

I don't. I just created a fresh Ocaml 4.11.0 switch on a virtual machine with:

- emacs fresh install,
- merlin 4.2-411
- tuareg 2.2.0
- user-setup

There is no Ocaml LSP server on this switch. I get this:

![image](https://user-images.githubusercontent.com/18618040/127298863-721f6fc9-6f03-4b95-be1a-e100d4475497.png)

**Comment by trefis** [comment]
Thanks for the screenshot!

The issue here is that the record fails to type as is (some fields are missing), and our recovery is not smart enough to keep the fields, so it drops the whole record.
We hope to improve on this at some point, but I don't know when that will happen.

**Comment by AllanBlanchard** [comment]
Argh, I took the wrong screenshot ... So with a well-typed record:

![image](https://user-images.githubusercontent.com/18618040/127461889-913eaea1-3c75-4afd-9640-8192160c16a4.png)

![image](https://user-images.githubusercontent.com/18618040/127462250-f8cd3f68-ec57-4f17-ba97-d962cdd40903.png)

**Comment by trefis** [comment]
Ah indeed!
Well this is fixed on master, since 24fa9a04648df92a1d3770e568762f8cf7db74c0 apparently. The fix is included in the 4.3 release which reached opam 3 days ago, so if you update, you should be good!

**Comment by AllanBlanchard** [comment]
Good to know! Thank you for your time :)
