### ISSUE TITLE
Merlin stoped working in version 3.3.2 for our project

### ISSUE THREAD

**Issue by modlfo** [ocaml/merlin#1011]
We recently updated from version 3.3.1 to 3.3.2 and we noticed that merlin stoped working.

We get thousands of "unbound module" and and many other errors. Since the project is big, it's hard to point out where the things start going bad.

We use Vim and VS Code plugins in the editors and both seem to be broken.

Is there a way that we can determine what's wrong?

**Comment by let-def** [comment]
You can produce a log file by setting `MERLIN_LOG=/tmp/merlin.log` (easier to do with vim I guess). The log will contain a lot of information, it helps if you can share it but you will want to filter sensitive content (mainly: input source, binding names and file paths).

**Comment by modlfo** [comment]
Can you send me please an email and I can send you the log file privately?

My email is public in my github profile.

**Comment by modlfo** [comment]
Seems like we found the problem. In our configuration file we had something like this to include all subfolders as part of the build directories.

```
B ./build/**
```

However the actual binary files were deeper into that directory in a path like `build/path1/dune/_build/default/.Program.eobjs`.

If we explicitly add that directory seems to work. Like this:

```
B ./build/path1/dune/_build/default/.Program.eobjs/**
```

We are using the new configuration and it works fine. Was that an intended change?

**Comment by trefis** [comment]
Yes, #990 .

Why isn't your .merlin generated by dune if you're using dune?

**Comment by modlfo** [comment]
@trefis Why? there are of lost of reasons. We haven't been able of making a good integration of Dune with the build system of our project (which is mostly not OCaml code). But so far Dune is the build system that has given us less problems.
